package com.example.drawzuiwei;

public class MyDate {
    public static String date = "{\n" +
            "    \"tableAllowance\":[\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"085\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":211,\n" +
            "            \"ypoint\":341,\n" +
            "            \"tableLableName\":\"靠窗\",\n" +
            "            \"tableStatus\":0\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"12\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":467,\n" +
            "            \"ypoint\":131,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":0\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"099\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":150,\n" +
            "            \"ypoint\":386,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":0\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"105\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":115,\n" +
            "            \"ypoint\":241,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"106\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":113,\n" +
            "            \"ypoint\":298,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":0\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"091\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":138,\n" +
            "            \"ypoint\":265,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"097\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":137,\n" +
            "            \"ypoint\":338,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"098\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":137,\n" +
            "            \"ypoint\":364,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":0\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"71\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":397,\n" +
            "            \"ypoint\":340,\n" +
            "            \"tableLableName\":\"近小料台,普通,靠窗\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"73\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":317,\n" +
            "            \"ypoint\":340,\n" +
            "            \"tableLableName\":\"靠窗\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"75\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":291,\n" +
            "            \"ypoint\":340,\n" +
            "            \"tableLableName\":\"靠窗\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"8\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":456,\n" +
            "            \"ypoint\":107,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"2\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":606,\n" +
            "            \"ypoint\":159,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"20\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":603,\n" +
            "            \"ypoint\":238,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"103\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":114,\n" +
            "            \"ypoint\":214,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"107\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":113,\n" +
            "            \"ypoint\":324,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"089\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":137,\n" +
            "            \"ypoint\":208,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"090\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":137,\n" +
            "            \"ypoint\":237,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"096\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":138,\n" +
            "            \"ypoint\":309,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"70\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":425,\n" +
            "            \"ypoint\":339,\n" +
            "            \"tableLableName\":\"近小料台,普通,靠窗\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"72\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":343,\n" +
            "            \"ypoint\":340,\n" +
            "            \"tableLableName\":\"靠窗\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"83\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":236,\n" +
            "            \"ypoint\":338,\n" +
            "            \"tableLableName\":\"靠窗\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"6\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":513,\n" +
            "            \"ypoint\":107,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"7\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":489,\n" +
            "            \"ypoint\":105,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"1\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":606,\n" +
            "            \"ypoint\":127,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"11\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":526,\n" +
            "            \"ypoint\":128,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"13\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":501,\n" +
            "            \"ypoint\":129,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"18\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":603,\n" +
            "            \"ypoint\":194,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"19\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":605,\n" +
            "            \"ypoint\":211,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"21\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":601,\n" +
            "            \"ypoint\":271,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"23\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":603,\n" +
            "            \"ypoint\":321,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"52\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":559,\n" +
            "            \"ypoint\":332,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"53\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":523,\n" +
            "            \"ypoint\":327,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"56\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":607,\n" +
            "            \"ypoint\":355,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"57\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":605,\n" +
            "            \"ypoint\":383,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"85\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":143,\n" +
            "            \"ypoint\":61,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"012\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":268,\n" +
            "            \"ypoint\":94,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"108\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":114,\n" +
            "            \"ypoint\":357,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"100\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":190,\n" +
            "            \"ypoint\":396,\n" +
            "            \"tableLableName\":\"近小料台\",\n" +
            "            \"tableStatus\":3\n" +
            "        },\n" +
            "        {\n" +
            "            \"storeId\":\"020120\",\n" +
            "            \"tableNo\":\"22\",\n" +
            "            \"capacity\":4,\n" +
            "            \"position\":0,\n" +
            "            \"xpoint\":604,\n" +
            "            \"ypoint\":295,\n" +
            "            \"tableLableName\":\"近小料台,普通\",\n" +
            "            \"tableStatus\":3\n" +
            "        }\n" +
            "    ]\n" +
            "}";
}